---
- name: Deploy RS-ALGO-SCREENER
  hosts: all
  roles:
    - { role: "deployment/git/roles" }
    - { role: "deployment/docker-registry/roles/" }
    - { role: "deployment/kubernetes-dashboard/roles/" }
    - { role: "deployment/mongodb/roles/" }
    - { role: "rs_algo_backend/deployment/roles/" }
    - { role: "rs_algo_scanner/deployment/roles/" }
    - { role: "rs_algo_client/deployment/roles/" }
