---
- name: Deploy RS-ALGO-SCREENER 
  hosts: all
  roles:
    - { role : 'deployment/roles/git' }
    - { role : 'deployment/rs-algo-mongodb/roles/deploy' }
    - { role : 'rs_algo_backend/roles/deploy' }
    - { role : 'rs_algo_backend/roles/deploy' }
    - { role : 'rs_algo_screener/roles/deploy' }
