---
- name: Deploy RS-ALGO-SCREENER 
  hosts: all
  roles:
    - { role : 'deployment/roles/git' }
    #- { role : 'deployment/rs-algo-mongodb/roles/deploy' }
    - { role : 'rs_algo_backend/deployment/roles/deploy' }
    - { role : 'rs_algo_screener/deployment/roles/deploy' }
