---
- name: Deploy RS-ALGO-SCREENER 
  hosts: all
  roles:
    - { role : 'deployment/git/roles' }
    - { role : 'deployment/mongodb/roles/' }
    - { role : 'rs_algo_backend/deployment/roles/' }
    - { role : 'rs_algo_screener/deployment/roles/' }
