pub mod bollinger_bands_reversal;
pub mod bollinger_bands_reversal_continuation;
pub mod bollinger_bands_riding_bands;
pub mod ema_200;
pub mod ema_50200;
pub mod macd;
pub mod mean_reversion;
pub mod stoch;
pub mod strategy;
