pub mod strategy;

// pub mod bollinger_bands_reversal;
// pub mod bollinger_bands_reversal_2;
// pub mod bollinger_bands_reversal_riding;
// pub mod bollinger_bands_reversal_riding_band_width;
// pub mod bollinger_bands_reversal_riding_rsi;
// pub mod bollinger_bands_reversals_continuation_ls_mt_macd;
// pub mod bollinger_bands_reversals_continuation_mt_macd;
// pub mod bollinger_bands_reversals_mt_macd;
// pub mod ema_200;
// pub mod ema_200_ls;
// pub mod ema_50;
// pub mod ema_50200;
// pub mod ema_50200_ls;
// pub mod ema_50200_ls_mt_macd;
// pub mod macd;
// pub mod macd_dual;
// pub mod macd_over_zero;
// pub mod macd_rsi;
// pub mod macd_weekly;
// pub mod rsi;
// pub mod stoch;
// pub mod stoch_ls;
// pub mod stoch_ls_mt_macd;

// pub mod bollinger_bands_reversal_continuation_ls;
// pub mod bollinger_bands_reversal_ls;
// pub mod bollinger_bands_reversal_riding_rsi_ls;
pub mod bollinger_bands_middle_band;
pub mod bollinger_bands_reversals;
pub mod ema_scalping;
pub mod ema_scalping2;
pub mod num_bars;
