[serve]
addr = "0.0.0.0"
port = 8080

[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"

[tools]
dotenv = "0.15.0"

[[proxy]]
rewrite = "/localhost:8080/api/instruments"
backend = "http://localhost:8000/api/instruments/"