[package]
name = "rs_algo_scanner"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_qs = "0.9.1"
dotenv = "0.15.0"
find_peaks = "0.1.4"
polyfit-rs="0.2.0"
ta = {version = "0.5.0", features = ["serde"] }
chrono = {version = "0.4.19",  features = ["serde"] }
async-trait = "0.1.52"
round = "0.1.2"
futures = "0.3.21"
reqwest = { version = "0.11.10", features = ["json"] }
openssl = { version = "0.10.38", features = ["vendored"] }
tungstenite = {version = "0.17.2", features = ["native-tls"]}

plotters = {git = "https://github.com/pmagaz/plotters", features = ["all_series"]}
rs_algo_shared = {git = "https://github.com/pmagaz/rs_algo_shared", rev = "8368577"}