[package]
name = "rs_algo_backend"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.1"
actix-http = "3.0.0"
anyhow = "1.0.54"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_qs ="0.9.1"
chrono = {version = "0.4.19",  features = ["serde"] }
thiserror = "1.0.30"
dotenv = "0.15.0"
lazy_static = "1.4"
bson = "2.1.0"
futures = "0.3.21"
reqwest = { version = "0.11.9", features = ["json"] }
openssl = { version = "0.10.38", features = ["vendored"] }
ta = {version = "0.5.0", features = ["serde"] }
rs_algo_shared = { git = "https://github.com/pmagaz/rs_algo_shared", rev = "154bb95"}

[dependencies.mongodb]
version = "2.1.0"
default-features = false
features = ["async-std-runtime"]

