[package]
name = "rs_algo_backend"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "3.3.3"
actix-http = "2.2.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_qs ="0.8.5"
chrono = "0.4.19"
thiserror = "1.0.30"
dotenv = "0.15.0"
lazy_static = "1.4"
bson = "2"
[dependencies.shared]
path = "../shared"

[dependencies.mongodb]
version = "2.1.0"
default-features = false
features = ["async-std-runtime"]

