jobs:
  - name: daily
    image:
      repository: pmagaz/rs-algo-scanner
      tag: latest
      imagePullPolicy: Always
    schedule: "0 */1,20,21,00,16:30 * * *"
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: Never
    activeDeadlineSeconds: 7200
    envSecretName: rs-algo-screener-secrets
    resources:
      requests:
        cpu: 800m
      limits:
        cpu: 1000m
        memory: 256Mi
    