jobs:
  - name: daily
    image:
      repository: pmagaz/rs-algo-scanner
      tag: latest
      imagePullPolicy: Always
    #schedule: "0 */4,10,17,18,21,22 * * *"
    schedule: "0 */4,10,17,18,20,21 * * *"
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: Never
    activeDeadlineSeconds: 7200
    envSecretName: rs-algo-screener-secrets
    resources:
      requests:
        cpu: 900m
      limits:
        cpu: 1000m
        memory: 256Mi
    
nodeSelector:
  storage: memory