jobs:
  - name: forex
    image:
      repository: cluster.loc:5000/rs-algo-backtest
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "0 4 * * 6"
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: Never
    activeDeadlineSeconds: 7200
    envSecretName: rs-algo-screener-secrets
    resources:
      requests:
        cpu: 800m
      limits:
        cpu: 1200m
        memory: 512Mi
    nodeSelector:
      nodeType: cpu
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nodeType
              operator: In
              values:
              - cpu
    
