replicaCount: 1

image:
  repository: pmagaz/docker-registry
  pullPolicy: "Always" 
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data

volumes:
- name: data
  hostPath:
    path: /data
    type: Directory

envSecretName: rs-algo-screener-secrets

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: LoadBalancer 
  port: 5000 
  targetPort: 5000 
  metadata:
    name: docker-registry
    labels:
      app: docker-registry

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
   #storage: 1Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: storage

tolerations: []

affinity: {}
