replicaCount: 1

image:
  repository: pmagaz/docker-registry
  pullPolicy: Always 
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /mnt/data

volumes:
- name: data
  persistentVolumeClaim:
        claimName: data-pvc-claim
  hostPath:
    path: /mnt/data
    type: Directory

envSecretName: rs-algo-screener-secrets

podAnnotations: {}

service:
  type: LoadBalancer
  port: 5000 
  targetPort: 5000
  #nodePort: 5000 
  metadata:
    name: docker-registry
    labels:
      app: docker-registry

serviceAccount: {}

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 200m
    #storage: 1Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType 
          operator: In
          values:
          - storage

tolerations: []

podSecurityContext: {}
