replicaCount: 1

image:
  repository: pmagaz/docker-registry
  pullPolicy: "IfNotPresent" 
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data

volumes:
- name: data
  hostPath:
    path: /data
    type: Directory

envSecretName: rs-algo-screener-secrets

podAnnotations: {}

service:
  type: NodePort 
  port: 5000 
  targetPort: 5000
  nodePort: 305000 
  metadata:
    name: docker-registry
    labels:
      app: docker-registry

serviceAccount: {}

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
    #storage: 1Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType 
          operator: In
          values:
          - storage

tolerations: []

podSecurityContext: {}
