apiVersion: v1
kind: Service
metadata:
  name: {{ include "rs-algo-backend.fullname" . }}
  labels:
    app: {{ .Values.service.metadata.labels.app }}
    {{- include "rs-algo-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http 
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }} 
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "rs-algo-backend.selectorLabels" . | nindent 4 }}
