ENV: "production"
BACkTEST_LIMIT_INSTRUMENTS: "20"
BACKTEST_MARKET: "Crypto"
BACKEND_INSTRUMENTS_ENDPOINT: "http://rs-algo-backend/api/instruments"
BACKEND_BACKTEST_ENDPOINT: "http://rs-algo-backend/api/backtest"
BACKEND_BACKTEST_INSTRUMENTS_ENDPOINT: "http://rs-algo-backend/api/backtest/instruments"
BACKEND_BACKTEST_STRATEGIES_ENDPOINT: "http://rs-algo-backend/api/backtest/strategies"