jobs:
  - name: crypto
    image:
      repository: cluster.loc:5000/rs-algo-backtest
      tag: latest
      imagePullPolicy: Always
    schedule: "30 4 * * 1"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    activeDeadlineSeconds: 7200
    envSecretName: rs-algo-screener-secrets
    resources:
      requests:
        cpu: 400m
      limits:
        cpu: 800m
        memory: 256Mi
    nodeSelector:
      nodeType: cpu
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nodeType
              operator: In
              values:
              - cpu
    
