apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-mem.fullname" . }}
  labels:
    app: {{ .Values.service.metadata.labels.app }}
    {{- include "mongodb-mem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mongodb-mem.selectorLabels" . | nindent 4 }}
