ENV: "production"
SCANNER_BACKTEST_MODE: "false"
LOGARITHMIC_SCANNER: "true"
RENDER_TO_IMAGE: "false"
SLEEP_TIME: "100"
NUM_TEST_BARS: "400"
BASE_TIME_FRAME: "D"
UPPER_TIME_FRAME: "W"
SYMBOLS_FILTER_LIST: ""
LOCAL_MIN_PROMINENCE: "0.035"
EXTREMA_MIN_PROMINENCE: "0.050"
LOCAL_PROMINENCE_MIN_DISTANCE: "10"
EXTREMA_PROMINENCE_MIN_DISTANCE: "20"
KERNEL_PRICE_SMOOTHING: "false"
KERNEL_REGRESSION_BANDWIDTH: "0.05"
DIVERGENCE_MIN_PROMINENCE: "0.02"
DIVERGENCE_PROMINENCE_MIN_DISTANCE: "10"
PRICE_SOURCE: "highs_lows"
AVG_VOLUME_DAYS: "30"
EQUAL_THRESHOLD: "0.018"
SLOPE_DEVIATION_THRESHOLD: "1"
PARALLEL_LINES_THRESHOLD: "5"
MAX_PATTERN_DAYS: "3"
MAX_PATTERN_ACTIVATED_DAYS: "3"
MIN_PATTERN_BARS: "10"
MINIMUM_PATTERN_TARGET: "15"
PATTERNS_WINDOW_SIZE: "4"
DIVERGENCES_WINDOW_SIZE: "3"
PATTERNS_MAX_POINTS: "1000"
PATTERNS_MIN_POINTS: "3"
DIVERGENCES_MIN_POINTS: "2"
EXTENDED_INDICATORS: "true"
EMA_A: "8"
EMA_B: "50"
EMA_C: "200"
GAP_THRESHOLD: "1.02"
HEAD_AND_SHOULDERS_THRESHOLD: "0.03"
HORIZONTAL_LEVELS_THRESHOLD: "1.8"
MIN_HORIZONTAL_LEVELS_OCCURENCES: "3"
PRICE_BREAK_CHECKPOINTS: "3"
LOCAL_PEAKS_MARKERS_POS: "0.04"
EXTREMA_PEAKS_MARKERS_POS: "0.08"
MIN_PRICE: "-100"
OUTPUT_FOLDER: "plotters/"
PLOTTER_FONT: "sans-serif"
BROKER_URL: "wss://ws.xtb.com/real"
BACKEND_INSTRUMENTS_ENDPOINT: "http://rs-algo-backend/api/instruments"
