jobs:
  - name: daily
    image:
      repository: cluster.loc:5000/rs-algo-scanner
      tag: latest
      imagePullPolicy: Always
    #schedule: "0 */12 * * *"
    schedule: "0 13 * * *"
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: Never
    activeDeadlineSeconds: 7200
    envSecretName: rs-algo-screener-secrets
    resources:
      requests:
        cpu: 600m
      limits:
        cpu: 700m
        memory: 256Mi
    nodeSelector:
      nodeType: cpu
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nodeType
              operator: In
              values:
              - cpu
    
