jobs:
  - name: daily
    image:
      repository: cluster.loc:5000/rs-algo-scanner
      tag: latest 
      imagePullPolicy: IfNotPresent
    schedule: "0 0 * * *"
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: Never
    activeDeadlineSeconds: 7200
    envSecretName: rs-algo-screener-secrets
    resources:
      requests:
        cpu: 400m
      limits:
        cpu: 500m
        memory: 256Mi
    nodeSelector:
      nodeType: cpu
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nodeType
              operator: In
              values:
              - cpu
    
