RENDER_TO_IMAGE: false
SLEEP_TIME: 200
LOCAL_MIN_PROMINENCE: 0.03
EXTREMA_MIN_PROMINENCE: 0.06
PROMINENCE_MIN_DISTANCE: 20
KERNEL_BANDWIDTH: 0.05
PATTERNS_WINDOW_SIZE: 5
PATTERNS_MAX_POINTS: 3
PATTERNS_MIN_POINTS: 3
EMA_A: 50
EMA_B: 21
EMA_C: 9
EQUAL_THRESHOLD: 1.5
LOWER_THRESHOLD: 0.4
INCREASE_THRESHOLD: 1.5
GAP_THRESHOLD: 1.02
HEAD_AND_SHOULDERS_THRESHOLD: 0.03
HORIZONTAL_LEVELS_THRESHOLD: 1.8
MIN_HIGHER_HIGHS: 3
MIN_HIGHER_LOWS: 2
MARKERS_DISTANCE: 180
MIN_PRICE: -100
OUTPUT_FOLDER: "plotters/"
BROKER_URL: "wss://ws.xtb.com/real"