replicaCount: 1

image:
  repository: pmagaz/rs-algo-screener 
  pullPolicy: Always
  tag: "latest"

envSecretName: rust-auth-secrets

imagePullSecrets:
 - name: docker-credentials 

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

resources: {}
  #requests:
  #  cpu: 100m
  #memory: 128Mi
  #limits:
  #  cpu: 100m
  #  memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
