jobs:
  - name: rs-algo-screener
    image:
      repository: pmagaz/rs-algo-screener
      tag: latest
      imagePullPolicy: Always
    schedule: "40 22 * * *"
    failedJobsHistoryLimit: 0
    successfulJobsHistoryLimit: 0
    concurrencyPolicy: Forbid
    restartPolicy: Never
    activeDeadlineSeconds: 360000
    envSecretName: rs-algo-screener-secrets
    resources:
  #   requests:
  #      cpu: 250m
      limits:
        cpu: 500m
        memory: 256Mi
    