replicaCount: 1

image:
  repository: arm64v8/mongo
  pullPolicy: "IfNotPresent" 
  tag: "4.4.12"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data

volumes:
- name: data
  hostPath:
    path: /data
    type: Directory

envSecretName: rs-algo-screener-secrets

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: LoadBalancer 
  port: 27018 
  targetPort: 27017 
  metadata:
    name: mongodb
    labels:
      app: mongodb

resources:
  requests:
     cpu: 200m
  limits:
    cpu: 400m
    storage: 1Gi
    memory: 256Mi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - storage

tolerations: []

