replicaCount: 1

image:
  repository: arm64v8/mongo
  pullPolicy: "IfNotPresent" 
  tag: "4.4.12"

volumeMounts:
- name: data
  mountPath: /data/db

volumes:
- name: data
  emptyDir:
      medium: Memory

envSecretName: rs-algo-screener-secrets

imagePullSecrets:
 - name: docker-credentials 

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: LoadBalancer 
  port: 27017 
  targetPort: 27017 
  metadata:
    name: mongodb
    labels:
      app: mongodb

resources:
  requests:
     cpu: 1300m
  limits:
    cpu: 1500m
    ephemeral-storage: 3Gi
    memory: 3Gi

ingress: {}

autoscaling: {}

nodeSelector: {}

tolerations: []

affinity: {}
