replicaCount: 1

image:
  repository: arm64v8/mongo
  pullPolicy: "IfNotPresent" 
  tag: "4.4.12"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data

volumes:
- name: data
  hostPath:
    path: /data
    type: Directory

envSecretName: rs-algo-screener-secrets

serviceAccount: {}

podAnnotations: {}

podSecurityContext: {}

service:
  type: NodePort 
  port: 27017
  targetPort: 27017 
  nodePort: 30018
  metadata:
    name: mongodb
    labels:
      app: mongodb

resources:
  requests:
     cpu: 200m
  limits:
    cpu: 300m
    #storage: 2Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - storage

tolerations: []

livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe: {}
