replicaCount: 1

image:
  repository: arm64v8/mongo
  pullPolicy: "IfNotPresent" 
  tag: "4.4.12"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data

volumes:
- name: data
  hostPath:
    path: /data
    type: Directory

envSecretName: rs-algo-screener-secrets

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: NodePort 
  port: 31448 
  targetPort: 27017
  metadata:
    name: mongodb
    labels:
      app: mongodb

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: cluster.loc
      paths:
      - path: /db/mongodb
        pathType: Prefix
        backend:
          service:
            name: mongodb 
            port:
              number: 31448

resources:
  requests:
     cpu: 200m
  limits:
    cpu: 300m
    #storage: 2Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - storage

tolerations: []

