replicaCount: 1

image:
  repository: arm64v8/mongo
  pullPolicy: "IfNotPresent" 
  tag: "4.4.12"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data/db

volumes:
- name: data
  emptyDir:
      medium: Memory

envSecretName: rs-algo-screener-secrets

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: LoadBalancer 
  port: 27017 
  targetPort: 27017 
  metadata:
    name: mongodb
    labels:
      app: mongodb

resources:
  requests:
     cpu: 800m
  limits:
    cpu: 1000m
    ephemeral-storage: 4Gi
    memory: 4Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: cpu

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - cpu

tolerations: []

