FROM_DATE: "730"
TIME_FRAME: "D"
LOCAL_MIN_PROMINENCE: "0.03"
EXTREMA_MIN_PROMINENCE: "0.06"
PROMINENCE_MIN_DISTANCE: "20"
DIVERGENCE_MIN_PROMINENCE: "0.02"
KERNEL_REGRESSION_SOURCE: "highs_lows"
KERNEL_REGRESSION_BANDWIDTH: "0.05"
PATTERNS_WINDOW_SIZE: "5"
PATTERNS_MAX_POINTS: "1000"
PATTERNS_MIN_POINTS: "3"
EMA_A: "200"
EMA_B: "100"
EMA_C: "50"
EMA_D: "21"
EMA_E: "9"
EQUAL_THRESHOLD: "1.5"
LOWER_THRESHOLD: "0.4"
INCREASE_THRESHOLD: "1.5"
GAP_THRESHOLD: "1.02"
HEAD_AND_SHOULDERS_THRESHOLD: "0.03"
HORIZONTAL_LEVELS_THRESHOLD: "1.8"
MIN_HIGHER_HIGHS: "3"
MIN_HIGHER_LOWS: "2"
MARKERS_DISTANCE: "180"
MIN_PRICE: "-100"
BACKEND_PORT: "8000"
BACKEND_NAME: "Rust Algo Backend"
BACKEND_DATABASE: "screener-db"
INSERT_INSTRUMENTS: "true"
INSERT_INSTRUMENTS_DETAIL: "true"
DB_INSTRUMENTS_COLLECTION: "instruments"
DB_INSTRUMENTS_DETAIL_COLLECTION: "instruments_detail"
DB_POSITIONS_COLLECTION: "positions"
PLOTTER_FONT: "monospace"
BACKEND_PLOTTER_OUTPUT_FOLDER: "/data/plotters/"
BACKEND_MONGO_DB_URI: "@mongodb:27017/screener-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"