BACKEND_PORT: "8000"
BACKEND_NAME: "Rust Algo Backend"
BACKEND_DATABASE: "screener-db"
INSERT_INSTRUMENTS: "true"
INSERT_INSTRUMENTS_DETAIL: "true"
DB_INSTRUMENTS_COLLECTION: "instruments"
DB_INSTRUMENTS_DETAIL_COLLECTION: "instruments_detail"
DB_POSITIONS_COLLECTION: "positions"
PLOTTER_FONT: "sans-serif"
BACKEND_PLOTTER_OUTPUT_FOLDER: "/data/plotters/"
LOCAL_PEAKS_MARKERS_POS: "0.04"
EXTREMA_PEAKS_MARKERS_POS: "0.08"
STOCH_BOTTOM: "25"
MINIMUM_PATTERN_TARGET: "15"
MIN_HORIZONTAL_LEVELS_OCCURENCES: "2"
EMA_CROSSOVER_THRESHOLD: "0.15"
MAX_PATTERN_DAYS: "7"
MAX_PATTERN_ACTIVATED_DAYS: "5"
BACKEND_MONGO_DB_URI: "@mongodb:27017/screener-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"