ENV: "production"
BACKEND_PORT: "8000"
BACKEND_NAME: "Rust Algo Backend"
INSERT_COMPACT_INSTRUMENTS: "true"
INSERT_COMPACT_INSTRUMENTS_DETAIL: "true"
TIME_FRAME: "M30"
PRICE_SOURCE: "highs_lows"
PLOTTER_FONT: "sans-serif"
DISPLAY_POINTS: "true"
BACKEND_PLOTTER_OUTPUT_FOLDER: "/data/plotters/"
LOCAL_PEAKS_MARKERS_POS: "0.04"
EXTREMA_PEAKS_MARKERS_POS: "0.08"
STOCH_BOTTOM: "25"
MINIMUM_PATTERN_TARGET: "15"
MIN_HORIZONTAL_LEVELS_OCCURENCES: "2"
AVG_VOLUME_DAYS: "30"
MIN_VOLUME: "25000000"
MAX_PATTERN_DAYS: "3"
MAX_PATTERN_ACTIVATED_DAYS: "3"
BACkTEST_LIMIT_INSTRUMENTS: "20"

MONGO_MEM_DB_NAME: "screener-db"
MONGO_MEM_DB_URI: "@mongodb-mem:27017/screener-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
#MONGO_MEM_DB_URI: "@mongodb-mem:27017/screener-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
DB_INSTRUMENTS_COMPACT_COLLECTION: "instruments_compact_D"
DB_INSTRUMENTS_COLLECTION: "instruments_D"
DB_BACKTEST_INSTRUMENTS_COLLECTION: "backtest_instruments"
DB_BACKTEST_INSTRUMENT_RESULT_COLLECTION: "backtest_instruments_result"
DB_BACKTEST_STRATEGY_RESULT_COLLECTION: "backtest_strategy_result"
DB_PRICING_COLLECTION: "backtest_pricing"
DB_POSITIONS_COLLECTION: "positions"

MONGO_HDD_DB_NAME: "watch-db"
MONGO_HDD_DB_URI: "@mongodb:27017/watch-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
#MONGO_HDD_DB_URI: "@mongodb:27017/watch-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
DB_WATCHLIST_COLLECTION: "watch-list"
DB_PORTFOLIO_COLLECTION: "portfolio"

MONGO_BOT_DB_NAME: "bot-db"
MONGO_BOT_DB_URI: "@mongodb-bot:27017/bot-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
BOT_COLLECTION: "bots"