replicaCount: 1

image:
  repository: cluster.loc:5000/rs-algo-backend 
  pullPolicy: Always 
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data/plotters/

volumes:
- name: data
  emptyDir:
      medium: Memory

envSecretName: rs-algo-screener-secrets

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  metadata:
    name: rs-algo-backend
    labels:
      app: rs-algo-backend

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: cluster.loc
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: rs-algo-backend 
            port:
              number: 80 
  tls: []

resources:
  requests:
    cpu: 1800m
  limits:
    cpu: 2200m
    ephemeral-storage: 256Mi 
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 25
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {} 

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - cpu

tolerations: []

