replicaCount: 1

image:
  repository: cluster.loc:5000/rs-algo-backend 
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data/plotters/

volumes:
- name: data
  emptyDir:
      medium: Memory

envSecretName: rs-algo-screener-secrets

podAnnotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  metadata:
    name: rs-algo-backend
    labels:
      app: rs-algo-backend

serviceAccount: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: cluster.loc
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: rs-algo-backend 
            port:
              number: 80 
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 1Mi 
  limits:
    cpu: 800m
    ephemeral-storage: 256Mi
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 95

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - storage

tolerations: []

podSecurityContext: {}