replicaCount: 1

image:
  repository: arm64v8/mongo
  pullPolicy: "IfNotPresent" 
  tag: "4.4.12"

imagePullSecrets:
 - name: docker-credentials 

volumeMounts:
- name: data
  mountPath: /data/db

volumes:
- name: data
  emptyDir:
      medium: Memory

envSecretName: rs-algo-screener-secrets

podAnnotations: {}


service:
  type: NodePort 
  port: 27017
  targetPort: 27017 
  nodePort: 30017
  metadata:
    name: mongodb-mem
    labels:
      app: mongodb-mem

serviceAccount: {}

resources:
  requests:
     cpu: 800m
  limits:
    cpu: 1200m
    ephemeral-storage: 4Gi
    memory: 4Gi

ingress: {}

autoscaling: {}

nodeSelector:
  nodeType: cpu

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - cpu

tolerations: []

livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe: {}

podSecurityContext: {}
