replicaCount: 1

image:
  repository: pmagaz/rs-algo-client 
  pullPolicy: Always 
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

envSecretName: rs-algo-screener-secrets

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  metadata:
    name: rs-algo-client
    labels:
      app: rs-algo-client

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: cluster.loc
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: rs-algo-client 
            port:
              number: 80
  tls: []

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 200m
    memory: 32Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 25
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  storage: persistent

tolerations: []

affinity: {}
