ENV: "production"
BACkTEST_LIMIT_INSTRUMENTS: "20"
BACKTEST_MARKET: "Stock"
BASE_TIME_FRAME: "D"
UPPER_TIME_FRAME: "W"
BACKEND_INSTRUMENTS_ENDPOINT: "http://rs-algo-backend/api/instruments"
BACKEND_BACKTEST_ENDPOINT: "http://rs-algo-backend/api/backtest"
BACKEND_BACKTEST_INSTRUMENTS_ENDPOINT: "http://rs-algo-backend/api/backtest/instruments"
BACKEND_BACKTEST_STRATEGIES_ENDPOINT: "http://rs-algo-backend/api/backtest/strategies"
BACKTEST_ORDER_SIZE: "1000"
BACKTEST_STOP_LOSS: "2"
BACKTEST_COMISSION: "0.2"
BACKTEST_EQUITY: "10000"