name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build rs-algo-backend
      run: docker build rs_algo_backend --tag pmagaz/rs-algo-backend:latest
    - name: Build rs-algo-screener
      run: docker build rs_algo_screener --tag pmagaz/rs-algo-screener:latest

    - name: Docker Push rs-algo-backend
      run: docker push pmagaz/rs-algo-backend:latest

    - name: Docker Push rs-algo-screener
      run: docker push pmagaz/rs-algo-screener:latest